apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      application: simple
  template:
    metadata:
      labels:
        application: simple
    spec:
      containers:
        - name: simple-backend
          image: simplebackend:local
          ports:
            - containerPort: 3000
        - name: simple-frontend
          image: simplefrontend:local
          ports:
            - containerPort: 80
        - name: debug
          image: debug:local
