apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    application: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      application: hello
  template:
    metadata:
      labels:
        application: hello
    spec:
      containers:
        - name: hello
          image: hellosite:local
          ports:
            - containerPort: 80
