apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: static-ingress
  namespace: static-dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /static/dev
            backend:
              serviceName: static-service
              servicePort: 80
